# Launch Fast API app

# Use the official Python base image
FROM python:3.12

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app directory contents to the working directory
COPY app .

# Expose the port on which the app will run
EXPOSE 9999

# Launch the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9999"]